CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    username VARCHAR(80) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('VENDEDOR', 'ADMINISTRADOR')),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE rutas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL UNIQUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(160) NOT NULL,
    telefono VARCHAR(30) NOT NULL,
    direccion VARCHAR(255) NOT NULL,
    ruta_id BIGINT NOT NULL REFERENCES rutas (id),
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE productos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(80) NOT NULL UNIQUE,
    nombre VARCHAR(160) NOT NULL,
    precio_costo BIGINT NOT NULL CHECK (precio_costo >= 0),
    precio_venta BIGINT NOT NULL CHECK (precio_venta >= 0),
    stock BIGINT NOT NULL DEFAULT 0,
    activo BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    fecha TIMESTAMP WITH TIME ZONE NOT NULL,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    estado_pago VARCHAR(20) NOT NULL CHECK (estado_pago IN ('PENDIENTE', 'PAGADO')),
    estado_venta VARCHAR(20) NOT NULL CHECK (estado_venta IN ('CONFIRMADA', 'ANULADA')),
    neto BIGINT NOT NULL CHECK (neto >= 0),
    tasa_iva NUMERIC(5, 4) NOT NULL CHECK (tasa_iva >= 0),
    iva BIGINT NOT NULL CHECK (iva >= 0),
    total BIGINT NOT NULL CHECK (total >= 0),
    version INTEGER NOT NULL DEFAULT 0 CHECK (version >= 0)
);

CREATE TABLE detalles_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL REFERENCES ventas (id),
    producto_id BIGINT NOT NULL REFERENCES productos (id),
    cantidad BIGINT NOT NULL CHECK (cantidad > 0),
    precio_unitario BIGINT NOT NULL CHECK (precio_unitario >= 0),
    subtotal BIGINT NOT NULL CHECK (subtotal >= 0),
    CONSTRAINT uk_detalle_venta_producto UNIQUE (venta_id, producto_id)
);

CREATE TABLE movimientos_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    venta_id BIGINT NOT NULL REFERENCES ventas (id),
    fecha TIMESTAMP WITH TIME ZONE NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('ABONO', 'DEVOLUCION')),
    monto BIGINT NOT NULL CHECK (monto > 0),
    forma_pago VARCHAR(20) NOT NULL CHECK (forma_pago IN ('EFECTIVO', 'TRANSFERENCIA')),
    anulado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE movimientos_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL UNIQUE,
    producto_id BIGINT NOT NULL REFERENCES productos (id),
    venta_id BIGINT REFERENCES ventas (id),
    fecha TIMESTAMP WITH TIME ZONE NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('VENTA', 'ANULACION', 'EDICION', 'ENTRADA', 'AJUSTE')),
    cantidad BIGINT NOT NULL CHECK (cantidad <> 0),
    observacion VARCHAR(500)
);

CREATE TABLE revisiones_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venta_id BIGINT NOT NULL REFERENCES ventas (id),
    numero_version INTEGER NOT NULL CHECK (numero_version >= 0),
    fecha_cambio TIMESTAMP WITH TIME ZONE NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    estado_venta VARCHAR(20) NOT NULL CHECK (estado_venta IN ('CONFIRMADA', 'ANULADA')),
    neto BIGINT NOT NULL CHECK (neto >= 0),
    tasa_iva NUMERIC(5, 4) NOT NULL CHECK (tasa_iva >= 0),
    iva BIGINT NOT NULL CHECK (iva >= 0),
    total BIGINT NOT NULL CHECK (total >= 0),
    CONSTRAINT uk_revision_venta_version UNIQUE (venta_id, numero_version)
);

CREATE TABLE detalles_revision_venta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision_id BIGINT NOT NULL REFERENCES revisiones_venta (id),
    producto_id BIGINT NOT NULL REFERENCES productos (id),
    cantidad BIGINT NOT NULL CHECK (cantidad > 0),
    precio_unitario BIGINT NOT NULL CHECK (precio_unitario >= 0),
    subtotal BIGINT NOT NULL CHECK (subtotal >= 0),
    CONSTRAINT uk_detalle_revision_producto UNIQUE (revision_id, producto_id)
);

CREATE INDEX idx_clientes_ruta ON clientes (ruta_id);
CREATE INDEX idx_ventas_fecha ON ventas (fecha);
CREATE INDEX idx_ventas_cliente ON ventas (cliente_id);
CREATE INDEX idx_detalles_producto ON detalles_venta (producto_id);
CREATE INDEX idx_movimientos_pago_venta ON movimientos_pago (venta_id);
CREATE INDEX idx_movimientos_stock_producto ON movimientos_stock (producto_id);
